general:
  debug: false

services:
  auth:
    send-link:
      email: "bhavarth1905kr@gmail.com"
    custom-token:
      token: "abbajabbajabba"
    signup:
      email: "testmail12456@testing.com"
      password: "password"
  bucket:
    upload:
      filename: "/home/bhavarth/blackhat_london/agneyastra/cmd/agneyastra/poc.txt"
  firestore:
    extract_data: false