general:
  debug: false

services:
  auth:
    send-link:
      email: "bhavarth1905kr@gmail.com"
    custom-token:
      token: ""
    signup:
      email: ""
      password: ""
  bucket:
    upload:
      filename: "/home/bhavarth/blackhat_london/agneyastra/cmd/agneyastra/poc.txt"
